server:
  host: ${SERVER_HOST:-localhost}
  port: ${SERVER_PORT:-8080}
  is_develop: ${IS_DEVELOP:-false}
database:
  driver: ${DB_DRIVER:-mysql}
  host: ${MYSQL_HOST:-localhost}
  port: ${MYSQL_PORT:-3306}
  db_name: ${MYSQL_DATABASE:-satellite}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
