// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

var TableNames = struct {
	Archive string
	Client  string
	Device  string
}{
	Archive: "archive",
	Client:  "client",
	Device:  "device",
}
